services:
  - type: web
    name: fix-my-elo
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TEAM2_PYTHON
        value: /usr/bin/python3
      - key: TEAM2_MODEL_PATH
        value: /app/Team2/model_files/model.pth
      - key: TEAM2_MODEL_URL
        value: https://huggingface.co/Khushi-Malik/fix-my-elo/resolve/main/SL_trained_stockfish_trained.pth
